/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/account/list/': RouteRecordInfo<'/account/list/', '/account/list', Record<never, never>, Record<never, never>>,
    '/account/profile/': RouteRecordInfo<'/account/profile/', '/account/profile', Record<never, never>, Record<never, never>>,
    '/analysis/customerOrder/': RouteRecordInfo<'/analysis/customerOrder/', '/analysis/customerOrder', Record<never, never>, Record<never, never>>,
    '/analysis/productOrder/': RouteRecordInfo<'/analysis/productOrder/', '/analysis/productOrder', Record<never, never>, Record<never, never>>,
    '/article/': RouteRecordInfo<'/article/', '/article', Record<never, never>, Record<never, never>>,
    '/article/edit': RouteRecordInfo<'/article/edit', '/article/edit', Record<never, never>, Record<never, never>>,
    '/auth/page/': RouteRecordInfo<'/auth/page/', '/auth/page', Record<never, never>, Record<never, never>>,
    '/auth/role/': RouteRecordInfo<'/auth/role/', '/auth/role', Record<never, never>, Record<never, never>>,
    '/auth/role/[id]/': RouteRecordInfo<'/auth/role/[id]/', '/auth/role/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/bottle/audit/': RouteRecordInfo<'/bottle/audit/', '/bottle/audit', Record<never, never>, Record<never, never>>,
    '/bottle/factory/': RouteRecordInfo<'/bottle/factory/', '/bottle/factory', Record<never, never>, Record<never, never>>,
    '/bottle/fill/': RouteRecordInfo<'/bottle/fill/', '/bottle/fill', Record<never, never>, Record<never, never>>,
    '/bottle/fillCheck/': RouteRecordInfo<'/bottle/fillCheck/', '/bottle/fillCheck', Record<never, never>, Record<never, never>>,
    '/bottle/fillPreCheck/': RouteRecordInfo<'/bottle/fillPreCheck/', '/bottle/fillPreCheck', Record<never, never>, Record<never, never>>,
    '/bottle/list/': RouteRecordInfo<'/bottle/list/', '/bottle/list', Record<never, never>, Record<never, never>>,
    '/bottle/qrCode/': RouteRecordInfo<'/bottle/qrCode/', '/bottle/qrCode', Record<never, never>, Record<never, never>>,
    '/bottle/scale/': RouteRecordInfo<'/bottle/scale/', '/bottle/scale', Record<never, never>, Record<never, never>>,
    '/bottle/specific/': RouteRecordInfo<'/bottle/specific/', '/bottle/specific', Record<never, never>, Record<never, never>>,
    '/business/complaint/list/': RouteRecordInfo<'/business/complaint/list/', '/business/complaint/list', Record<never, never>, Record<never, never>>,
    '/business/refund/list/': RouteRecordInfo<'/business/refund/list/', '/business/refund/list', Record<never, never>, Record<never, never>>,
    '/business/repair/list/': RouteRecordInfo<'/business/repair/list/', '/business/repair/list', Record<never, never>, Record<never, never>>,
    '/company/car/list/': RouteRecordInfo<'/company/car/list/', '/company/car/list', Record<never, never>, Record<never, never>>,
    '/company/list/': RouteRecordInfo<'/company/list/', '/company/list', Record<never, never>, Record<never, never>>,
    '/company/store/list/': RouteRecordInfo<'/company/store/list/', '/company/store/list', Record<never, never>, Record<never, never>>,
    '/customer/analysis/': RouteRecordInfo<'/customer/analysis/', '/customer/analysis', Record<never, never>, Record<never, never>>,
    '/customer/edit/': RouteRecordInfo<'/customer/edit/', '/customer/edit', Record<never, never>, Record<never, never>>,
    '/customer/list/': RouteRecordInfo<'/customer/list/', '/customer/list', Record<never, never>, Record<never, never>>,
    '/customer/register/': RouteRecordInfo<'/customer/register/', '/customer/register', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/debug/': RouteRecordInfo<'/debug/', '/debug', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/mapLocation/bottle/': RouteRecordInfo<'/mapLocation/bottle/', '/mapLocation/bottle', Record<never, never>, Record<never, never>>,
    '/mapLocation/customer/': RouteRecordInfo<'/mapLocation/customer/', '/mapLocation/customer', Record<never, never>, Record<never, never>>,
    '/mapLocation/station/': RouteRecordInfo<'/mapLocation/station/', '/mapLocation/station', Record<never, never>, Record<never, never>>,
    '/order/delivery/': RouteRecordInfo<'/order/delivery/', '/order/delivery', Record<never, never>, Record<never, never>>,
    '/order/guaranty/list/': RouteRecordInfo<'/order/guaranty/list/', '/order/guaranty/list', Record<never, never>, Record<never, never>>,
    '/order/guaranty/setting/': RouteRecordInfo<'/order/guaranty/setting/', '/order/guaranty/setting', Record<never, never>, Record<never, never>>,
    '/order/guaranty/summary/': RouteRecordInfo<'/order/guaranty/summary/', '/order/guaranty/summary', Record<never, never>, Record<never, never>>,
    '/order/list/': RouteRecordInfo<'/order/list/', '/order/list', Record<never, never>, Record<never, never>>,
    '/order/monthly/': RouteRecordInfo<'/order/monthly/', '/order/monthly', Record<never, never>, Record<never, never>>,
    '/order/summary/': RouteRecordInfo<'/order/summary/', '/order/summary', Record<never, never>, Record<never, never>>,
    '/print/': RouteRecordInfo<'/print/', '/print', Record<never, never>, Record<never, never>>,
    '/product/customerDiscount/': RouteRecordInfo<'/product/customerDiscount/', '/product/customerDiscount', Record<never, never>, Record<never, never>>,
    '/product/list/': RouteRecordInfo<'/product/list/', '/product/list', Record<never, never>, Record<never, never>>,
    '/product/price/delivery/': RouteRecordInfo<'/product/price/delivery/', '/product/price/delivery', Record<never, never>, Record<never, never>>,
    '/product/price/floor/': RouteRecordInfo<'/product/price/floor/', '/product/price/floor', Record<never, never>, Record<never, never>>,
    '/product/price/store/': RouteRecordInfo<'/product/price/store/', '/product/price/store', Record<never, never>, Record<never, never>>,
    '/product/type/': RouteRecordInfo<'/product/type/', '/product/type', Record<never, never>, Record<never, never>>,
    '/redirect/401': RouteRecordInfo<'/redirect/401', '/redirect/401', Record<never, never>, Record<never, never>>,
    '/redirect/404': RouteRecordInfo<'/redirect/404', '/redirect/404', Record<never, never>, Record<never, never>>,
    '/riskManage/bottleMissing/': RouteRecordInfo<'/riskManage/bottleMissing/', '/riskManage/bottleMissing', Record<never, never>, Record<never, never>>,
    '/riskManage/bottleSummary/': RouteRecordInfo<'/riskManage/bottleSummary/', '/riskManage/bottleSummary', Record<never, never>, Record<never, never>>,
    '/riskManage/bottleWhere/': RouteRecordInfo<'/riskManage/bottleWhere/', '/riskManage/bottleWhere', Record<never, never>, Record<never, never>>,
    '/security/record/': RouteRecordInfo<'/security/record/', '/security/record', Record<never, never>, Record<never, never>>,
    '/security/template/detail/': RouteRecordInfo<'/security/template/detail/', '/security/template/detail', Record<never, never>, Record<never, never>>,
    '/security/template/list/': RouteRecordInfo<'/security/template/list/', '/security/template/list', Record<never, never>, Record<never, never>>,
    '/system/companyConfig/': RouteRecordInfo<'/system/companyConfig/', '/system/companyConfig', Record<never, never>, Record<never, never>>,
    '/system/config/': RouteRecordInfo<'/system/config/', '/system/config', Record<never, never>, Record<never, never>>,
    '/system/config/customer': RouteRecordInfo<'/system/config/customer', '/system/config/customer', Record<never, never>, Record<never, never>>,
    '/system/config/staff': RouteRecordInfo<'/system/config/staff', '/system/config/staff', Record<never, never>, Record<never, never>>,
    '/system/dict': RouteRecordInfo<'/system/dict', '/system/dict', Record<never, never>, Record<never, never>>,
    '/system/handleLog': RouteRecordInfo<'/system/handleLog', '/system/handleLog', Record<never, never>, Record<never, never>>,
    '/workspace/': RouteRecordInfo<'/workspace/', '/workspace', Record<never, never>, Record<never, never>>,
  }
}
