export const bottleSpecificList = [
  {
    name: "2kg",
    bottleType: "YSP4.7",
    innerDiameter: 200.0,
    volume: 4.7,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 1.6,
    NominalThickness: 2.0,
    maxFillingWeight: 1.9,
    emptyWeight: 3.4,
    GasCylinderHeight: 305.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 1,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "5kg",
    bottleType: "YSP12",
    innerDiameter: 244.0,
    volume: 12.0,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.0,
    NominalThickness: 2.5,
    maxFillingWeight: 5.0,
    emptyWeight: 7.0,
    GasCylinderHeight: 430.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 2,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "10kg",
    bottleType: "YSP23.5",
    innerDiameter: 314.0,
    volume: 23.5,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 9.8,
    emptyWeight: 13.0,
    GasCylinderHeight: 526.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 3,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "12kg",
    bottleType: "YSP26.2",
    innerDiameter: 294.0,
    volume: 26.2,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.4,
    NominalThickness: 3.0,
    maxFillingWeight: 11.0,
    emptyWeight: 15.0,
    GasCylinderHeight: 595.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 4,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "典型出口规格",
  },
  {
    name: "13kg",
    bottleType: "YSP32.2",
    innerDiameter: 314.0,
    volume: 32.2,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 13.5,
    emptyWeight: 16.0,
    GasCylinderHeight: 610.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 5,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "典型出口规格",
  },
  {
    name: "15kg",
    bottleType: "YSP35.5",
    innerDiameter: 314.0,
    volume: 35.5,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 14.9,
    emptyWeight: 16.5,
    GasCylinderHeight: 680.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 6,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "49kg",
    bottleType: "YSP108",
    innerDiameter: 374.0,
    volume: 108.0,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 3.5,
    NominalThickness: 3.0,
    maxFillingWeight: 45.0,
    emptyWeight: 38.0,
    GasCylinderHeight: 1216.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 7,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "典型出口规格",
  },
  {
    name: "50kg",
    bottleType: "YSP118",
    innerDiameter: 400.0,
    volume: 118.0,
    GasCylinderMaterialBrand: "HP325",
    designThickness: 2.9,
    NominalThickness: 3.5,
    maxFillingWeight: 49.5,
    emptyWeight: 47.0,
    GasCylinderHeight: 1200.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 8,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "气相和液相",
  },
  {
    name: "3kg",
    bottleType: "YSP7.3",
    innerDiameter: 260.0,
    volume: 7.3,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.3,
    NominalThickness: 2.0,
    maxFillingWeight: 3.0,
    emptyWeight: 4.89,
    GasCylinderHeight: 295.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 9,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "典型出口规格",
  },
  {
    name: "6kg",
    bottleType: "YSP14.6",
    innerDiameter: 294.0,
    volume: 14.6,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 2.3,
    maxFillingWeight: 6.0,
    emptyWeight: 9.5,
    GasCylinderHeight: 334.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 10,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "典型出口规格",
  },
  {
    name: "16kg",
    bottleType: "YSP35.7",
    innerDiameter: 314.0,
    volume: 35.7,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 3.0,
    NominalThickness: 2.7,
    maxFillingWeight: 15.0,
    emptyWeight: 17.2,
    GasCylinderHeight: 675.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 11,
    auditCycle: 4,
    yearLimit: 12,
    Remark: "典型出口规格",
  },
  {
    name: "100L车载钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 100.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 12,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "100L氧钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 100.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 13,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "100L乙炔瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 100.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 14,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "15kg车载钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 15,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "15kg氧钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 16,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "15kg乙炔瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 17,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "50kg车载钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 18,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "50kg乙炔瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 19,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "5kg车载钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 20,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "5kg氧钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 21,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "5kg乙炔瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 22,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "杜瓦罐",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 23,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "100L（15）",
    bottleType: null,
    innerDiameter: null,
    volume: 100.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 35.0,
    waterPressure: 52.5,
    order: 24,
    auditCycle: 3,
    yearLimit: 15,
  },
  {
    name: "100L钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 100.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.8,
    NominalThickness: 2.8,
    maxFillingWeight: 35.6,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 25,
    auditCycle: 5,
    yearLimit: 15,
  },
  {
    name: "107L焊接钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 107.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 26,
    auditCycle: 4,
    yearLimit: 15,
  },
  {
    name: "115L钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 115.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.8,
    NominalThickness: 2.8,
    maxFillingWeight: 34.0,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 27,
    auditCycle: 5,
    yearLimit: 15,
  },
  {
    name: "140L",
    bottleType: null,
    innerDiameter: null,
    volume: 140.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 28,
    auditCycle: 3,
    yearLimit: 15,
  },
  {
    name: "175L钢制无缝钢瓶（2-15）",
    bottleType: null,
    innerDiameter: null,
    volume: 175.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 29,
    auditCycle: 2,
    yearLimit: 15,
  },
  {
    name: "195L焊接绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 195.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 30,
    auditCycle: 3,
    yearLimit: 15,
  },
  {
    name: "210L焊接绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 210.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 31,
    auditCycle: 3,
    yearLimit: 15,
  },
  {
    name: "330L钢制无缝钢瓶（2-15）",
    bottleType: null,
    innerDiameter: null,
    volume: 330.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 32,
    auditCycle: 2,
    yearLimit: 15,
  },
  {
    name: "335L钢制无缝钢瓶（2-15）",
    bottleType: null,
    innerDiameter: null,
    volume: 335.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 33,
    auditCycle: 2,
    yearLimit: 15,
  },
  {
    name: "375L钢制无缝钢瓶（2-15）",
    bottleType: null,
    innerDiameter: null,
    volume: 375.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 34,
    auditCycle: 2,
    yearLimit: 15,
  },
  {
    name: "80L钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 80.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.5,
    NominalThickness: 2.5,
    maxFillingWeight: 28.5,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 35,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "80L天燃气钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 80.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 36,
    auditCycle: 1,
    yearLimit: 15,
  },
  {
    name: "90L钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 90.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.5,
    NominalThickness: 2.5,
    maxFillingWeight: 31.7,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 37,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "80L09钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 80.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 38,
    auditCycle: 3,
    yearLimit: 18,
  },
  {
    name: "80L16钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 80.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 39,
    auditCycle: 3,
    yearLimit: 18,
  },
  {
    name: "118L丁烷（3-20）",
    bottleType: "YSP118",
    innerDiameter: 400.0,
    volume: 118.0,
    GasCylinderMaterialBrand: null,
    designThickness: 3.3,
    NominalThickness: 3.3,
    maxFillingWeight: 49.0,
    emptyWeight: 48.0,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 40,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "15KG丙烷瓶",
    bottleType: "YSP40.0",
    innerDiameter: 0.0,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.6,
    NominalThickness: null,
    maxFillingWeight: 0.0,
    emptyWeight: 20.0,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 41,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "175L的焊接绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 175.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 42,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "175L低温绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 175.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 43,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "176L低温绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 176.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 44,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "195L低温绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 195.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 45,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "210L低温绝热钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 210.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 46,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "30KG丙烷瓶",
    bottleType: "YSP74.0",
    innerDiameter: 0.0,
    volume: 74.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.6,
    NominalThickness: null,
    maxFillingWeight: 0.0,
    emptyWeight: 30.4,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 47,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "400L瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 400.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 48,
    auditCycle: 4,
    yearLimit: 20,
  },
  {
    name: "40L钢制无缝钢瓶（3-20）",
    bottleType: null,
    innerDiameter: null,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 49,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "40L钢制无缝钢瓶（5-20）",
    bottleType: null,
    innerDiameter: null,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 50,
    auditCycle: 5,
    yearLimit: 20,
  },
  {
    name: "47L瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 47.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 51,
    auditCycle: 4,
    yearLimit: 20,
  },
  {
    name: "50KG丙烷瓶",
    bottleType: "YSP119.0",
    innerDiameter: 0.0,
    volume: 119.0,
    GasCylinderMaterialBrand: null,
    designThickness: 3.0,
    NominalThickness: null,
    maxFillingWeight: 0.0,
    emptyWeight: 50.4,
    GasCylinderHeight: null,
    generalPressure: 2.2,
    waterPressure: 3.3,
    order: 52,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "50L钢制无缝钢瓶（3-20）",
    bottleType: null,
    innerDiameter: null,
    volume: 50.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 53,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "50L钢制无缝钢瓶（5-20）",
    bottleType: null,
    innerDiameter: null,
    volume: 50.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 54,
    auditCycle: 5,
    yearLimit: 20,
  },
  {
    name: "800L瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 800.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 55,
    auditCycle: 4,
    yearLimit: 20,
  },
  {
    name: "T瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 56,
    auditCycle: 4,
    yearLimit: 20,
  },
  {
    name: "Y瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 57,
    auditCycle: 4,
    yearLimit: 20,
  },
  {
    name: "100L",
    bottleType: null,
    innerDiameter: null,
    volume: 100.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 58,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "10升",
    bottleType: null,
    innerDiameter: null,
    volume: 10.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 59,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "10升钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 10.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 60,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "15升",
    bottleType: null,
    innerDiameter: null,
    volume: 15.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 61,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "15升钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 15.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 62,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "400L",
    bottleType: null,
    innerDiameter: null,
    volume: 400.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 63,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "40L钢制无缝钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 64,
    auditCycle: 5,
    yearLimit: 30,
  },
  {
    name: "40L钢制无缝钢瓶（3-30）",
    bottleType: null,
    innerDiameter: null,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 65,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "40升",
    bottleType: null,
    innerDiameter: null,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 66,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "40升钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 40.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 67,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "450L",
    bottleType: null,
    innerDiameter: null,
    volume: 450.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 68,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "4升",
    bottleType: null,
    innerDiameter: null,
    volume: 4.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 69,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "50kg氮钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 70,
    auditCycle: 4,
    yearLimit: 30,
  },
  {
    name: "50kg二氧化碳钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 71,
    auditCycle: 2,
    yearLimit: 30,
  },
  {
    name: "50kg混合钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 72,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "50kg氩钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 73,
    auditCycle: 4,
    yearLimit: 30,
  },
  {
    name: "50kg氧钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: null,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 74,
    auditCycle: 4,
    yearLimit: 30,
  },
  {
    name: "50L",
    bottleType: null,
    innerDiameter: null,
    volume: 50.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 75,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "5升钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 5.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 76,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "6升",
    bottleType: null,
    innerDiameter: null,
    volume: 6.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 77,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "926L",
    bottleType: null,
    innerDiameter: null,
    volume: 926.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 78,
    auditCycle: 3,
    yearLimit: 30,
  },
  {
    name: "118L工业液化石油气（3-8）",
    bottleType: null,
    innerDiameter: null,
    volume: 118.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 79,
    auditCycle: 3,
    yearLimit: 8,
  },
  {
    name: "12升液化二甲醚钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 12.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.1,
    NominalThickness: 2.1,
    maxFillingWeight: 6.2,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 1.6,
    waterPressure: 2.4,
    order: 80,
    auditCycle: 4,
    yearLimit: 8,
  },
  {
    name: "26L",
    bottleType: null,
    innerDiameter: null,
    volume: 26.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 81,
    auditCycle: 4,
    yearLimit: 8,
  },
  {
    name: "30L钢制无缝钢瓶（4-8）",
    bottleType: null,
    innerDiameter: null,
    volume: 30.0,
    GasCylinderMaterialBrand: null,
    designThickness: null,
    NominalThickness: null,
    maxFillingWeight: null,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: null,
    waterPressure: null,
    order: 82,
    auditCycle: 4,
    yearLimit: 8,
  },
  {
    name: "35升液化二甲醚钢瓶",
    bottleType: null,
    innerDiameter: null,
    volume: 35.0,
    GasCylinderMaterialBrand: null,
    designThickness: 2.1,
    NominalThickness: 2.1,
    maxFillingWeight: 16.0,
    emptyWeight: null,
    GasCylinderHeight: null,
    generalPressure: 1.6,
    waterPressure: 2.4,
    order: 83,
    auditCycle: 4,
    yearLimit: 8,
  },
  {
    name: "16.5kg",
    bottleType: "YSP35.8",
    innerDiameter: 314.0,
    volume: 35.7,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 16.5,
    emptyWeight: 17.2,
    GasCylinderHeight: 675.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 84,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "20kg",
    bottleType: "YSP23.5",
    innerDiameter: 375.0,
    volume: 35.7,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 23.5,
    emptyWeight: 23.5,
    GasCylinderHeight: 780.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 85,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "12kg(29.8)",
    bottleType: "YSP29.8",
    innerDiameter: 294.0,
    volume: 29.8,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.2,
    NominalThickness: 3.0,
    maxFillingWeight: 12.4,
    emptyWeight: 14.0,
    GasCylinderHeight: 595.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 86,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "12kg(28.6)",
    bottleType: "YSP28.6",
    innerDiameter: 294.0,
    volume: 28.6,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 12.0,
    emptyWeight: 14.0,
    GasCylinderHeight: 595.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 87,
    auditCycle: 4,
    yearLimit: 12,
  },
  {
    name: "20kg丙烷瓶",
    bottleType: "HJL-48",
    innerDiameter: 300.0,
    volume: 48.0,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.0,
    NominalThickness: 2.0,
    maxFillingWeight: 19.5,
    emptyWeight: 22.0,
    GasCylinderHeight: 780.0,
    generalPressure: 2.22,
    waterPressure: 3.3,
    order: 88,
    auditCycle: 3,
    yearLimit: 20,
  },
  {
    name: "12kg(29.1)",
    bottleType: "YSP29.1",
    innerDiameter: 294.0,
    volume: 29.1,
    GasCylinderMaterialBrand: "HP295",
    designThickness: 2.5,
    NominalThickness: 3.0,
    maxFillingWeight: 12.4,
    emptyWeight: 14.0,
    GasCylinderHeight: 595.0,
    generalPressure: 2.1,
    waterPressure: 3.2,
    order: 89,
    auditCycle: 4,
    yearLimit: 12,
  },
]
